/**
 * 用于演示的 JSON 树形数据结构
 */
var root = {
    name:'D盘',
    children:[
        {
            name:'学习',
            children:[
                {
                    name:'电子书',
                    children:[
                        {
                            name:'文学',
                            children:[
                                {
                                    name:'茶馆'
                                },
                                {
                                  name:'红与黑'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            name:'电影',
            children:[
                {
                    name:'美国电影'
                },
                {
                    name:'日本电影'
                }
            ]
        }
    ]
}